// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa1V1J3fElUo4bn6P7aAzoEtQYJlCllio',
    appId: '1:792151502069:web:7a358f3c0d5675798d69bc',
    messagingSenderId: '792151502069',
    projectId: 'signin-b0256',
    authDomain: 'signin-b0256.firebaseapp.com',
    storageBucket: 'signin-b0256.appspot.com',
    measurementId: 'G-27QH0T0LTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK2YzreNUP12J8Axy9IbCX28MzmR1-gwo',
    appId: '1:792151502069:android:9dbffe8b8be8cd108d69bc',
    messagingSenderId: '792151502069',
    projectId: 'signin-b0256',
    storageBucket: 'signin-b0256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8ELPmTbMqR3gE-9dKmQPWY3FtrO3Ufg',
    appId: '1:792151502069:ios:c3c913cbe1d80a598d69bc',
    messagingSenderId: '792151502069',
    projectId: 'signin-b0256',
    storageBucket: 'signin-b0256.appspot.com',
    iosBundleId: 'com.example.pcd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8ELPmTbMqR3gE-9dKmQPWY3FtrO3Ufg',
    appId: '1:792151502069:ios:ecbbe0a7a72872278d69bc',
    messagingSenderId: '792151502069',
    projectId: 'signin-b0256',
    storageBucket: 'signin-b0256.appspot.com',
    iosBundleId: 'com.example.pcd.RunnerTests',
  );
}
