// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8acKCNyP5WcxvUxZj-w98Ppj7GpN8i_4',
    appId: '1:568293525742:web:d251bbb15d7bb2c5b48bff',
    messagingSenderId: '568293525742',
    projectId: 'mentalhealth-bc027',
    authDomain: 'mentalhealth-bc027.firebaseapp.com',
    storageBucket: 'mentalhealth-bc027.appspot.com',
    measurementId: 'G-VWHT55KYPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPqFDuc7mVbxSzqCqjaQLkfEXXtvXa2k',
    appId: '1:568293525742:android:0c2fdbe5a6de0a77b48bff',
    messagingSenderId: '568293525742',
    projectId: 'mentalhealth-bc027',
    storageBucket: 'mentalhealth-bc027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDkLuA-NWcNKLUKOpOT6DXR2qAHktqPsA',
    appId: '1:568293525742:ios:72d7b8e21da423e2b48bff',
    messagingSenderId: '568293525742',
    projectId: 'mentalhealth-bc027',
    storageBucket: 'mentalhealth-bc027.appspot.com',
    iosBundleId: 'com.example.ttoui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDkLuA-NWcNKLUKOpOT6DXR2qAHktqPsA',
    appId: '1:568293525742:ios:1e2e93627b8735cab48bff',
    messagingSenderId: '568293525742',
    projectId: 'mentalhealth-bc027',
    storageBucket: 'mentalhealth-bc027.appspot.com',
    iosBundleId: 'com.example.ttoui.RunnerTests',
  );
}
